theme: "hugo-PaperMod"
baseURL: https://www.callumsavage.com.au/
languageCode: en-us
title: Callum Savage
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true
  
assets:
  disableHLJS: false
  favicon: "static/favicon.io"

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About
          url: about/
          weight: 10
        - name: Tags
          url: tags/
          weight: 20
        - name: Search
          url: search/
          weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: "Callum Savage"
  description: "Callum Savage's personal website"
  author: "Callum Savage"
  DateFormat: January 2, 2006
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  disableAnchoredHeadings: true
  hideSummary: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: false
  comments: false

  homeInfoParams:
    Title: "Hello!"
    Content: >
        Welcome to my website :)
  socialIcons:
    - name: email
      url: "mailto:callum.savage@anu.edu.au"
    - name: github
      url: "https://github.com/callum-savage"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/11993091/callum-savage"
    - name: linkedin
      url: "https://www.linkedin.com/in/callum-savage/"
  editPost:
    URL: "https://github.com/callum-savage/callumsavage/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

markup:
  goldmark:
    renderer:
      unsafe: true
      
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

permalinks:
  post: "/:year/:month/:day/:slug/"
