---
title: Unpicking the Terminology of Ecological Forecasting
author: Callum Savage
date: '2022-01-14'
slug: ecological-forecasting-terminology
categories: []
tags:
  - ecological forecasting
summary: When is it a prediction, and when is it a forecast?
showToc: no
tocopen: no
hidemeta: no
comments: no
disableShare: yes
disableAnchoredHeadings: no
searchHidden: no
hideSummary: no
ShowPostNavLinks: yes
cover:
  image: <image path/url>
  alt: <cover image alt text>
  caption: <caption under cover image>
  relative: no
  hidden: yes
weight: 5
draft: yes
bibliography: references.bib
link-citations: yes
csl: nature
---

## Introduction

I am currently writing a review article on ecological forecasting, and there's a particular barrier I have come up against, again and again: not only is the concept of ecological forecasting loosely defined as a field, so too are the very terms 'ecological' and 'forecasting'. Sometimes, what I would consider a forecast is referred to as a 'prediction' or 'simulation'. Other times the opposite is true, and what I would consider a 'projection' is referred to as a 'forecast'.

This led me to really consider exactly what I meant when I say ecological forecasting. And I found I didn't have a solid definition. At least, not one that I was confident was shared by at least part of the ecological forecasting community.

Thus this blog post, where I intend to round up some of the (often contradictory) ways in which different researches use the terms 'prediction', 'forecast', and 'projection', amongst others. I hope this might be useful to others entering into this field, who have found themselves as befuddles as I am.

## Usage throughout the literature

### IPCC

The Intergovernmental Panel on Climate Change (IPCC), whilst not explicitly an ecological forecasting body, is influential in the forecasting world. Their focus is specifically on longer term climate change, and so their language usage reflects this.

In the parlance of the IPCC, a prediction or forecast is our best assessment of what is likely to happen in the future.

Following the definitions from the IPCC's most recent Assessment Report on the physical science basis for climate change (in press),

A climate prediction or climate forecast is the result of an attempt to produce (starting

25 from a particular state of the climate system) an estimate of the actual evolution of the climate in the future,

26 for example, at seasonal, interannual or decadal time scales. Because the future evolution of the climate

27 system may be highly sensitive to initial conditions, has chaotic elements and is subject to natural

28 variability, such predictions are usually probabilistic in nature.

> A **climate prediction** or **climate forecast** is the result of an attempt to produce a most likely description or estimate of the actual evolution of the climate in the future.

A projection, on the other hand, is a statement about the future contingent upon a particular scenario, the likelihood of which is not part of the projection.

> A **projection** is a potential future evolution of a quantity or set of quantities, often computed with the aid of a model. Unlike predictions, projections are conditional on assumptions concerning, for example, future socio-economic and technological developments that may or may not be realized. [@masson-delmotte2018]

Note that not just anything can be a scenario. A scenario should be based on a "coherent and internally consistent set of assumptions about key driving forces" [@masson-delmotte2018a].

These definitions are interesting, as they define a forecast and a prediction synonymously. As such, they are perhaps closest to the usage of the terms by the general public, and there is a certain appeal in sidestepping the conflicting definitions all together.

### The Ecological Forecasting Institute

## Summary

## References
